### ISSUE TITLE
vizjs in eclipse OSGi is not working

### ISSUE THREAD

**Issue by colameo** [plantuml/vizjs#1]
I'm trying to integrate vizjs as described in http://plantuml.com/vizjs but in an eclipse plugin. 

In the vm args I start eclipse with the system property **-DGRAPHVIZ_DOT=vizjs**.

When I start eclipse I get the following exception:
!ENTRY org.eclipse.core.net 1 0 2018-02-04 13:30:35.861
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
java.io.IOException: Cannot run program "/Users/serano/Development/eclipse/4.7/eclipse-jhipster-ide/Eclipse.app/Contents/MacOS/vizjs": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:162)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:122)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:78)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
java.io.IOException: Cannot run program "/Users/serano/Development/eclipse/4.7/eclipse-jhipster-ide/Eclipse.app/Contents/MacOS/vizjs": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:162)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:122)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:78)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more

So I guess the vizjs.jar is not working in an OSGi environment and the reason for the exception above is because of classloading problem, right? However, the "**java.io.IOException: Cannot run program**" is anyway strange... apparently PlantUML with the option **GRAPHVIZ_DOT=vizjs** tries to run a program called "vizjs".

**Comment by boessu** [comment]
Yes, I think you have a classloader problem. But not here in vizjs.jar.
Basically the exception happens in PlantUml at this line (I'm sorry to say that's a bit of a guess as I don't know which version of plantuml you're running, but that would be logical):
`
process = Runtime.getRuntime().exec(cmd, null, dir);
`
So it seems as it tries to run the GraphViz executable on your machine which doesn't exist.

So plantuml.jar didn't load the classes in vizjs.jar and the according V8 engine jar.

plantuml.jar tries to load additional libraries with his MANIFEST.MF:
```
Class-Path: avalon-framework-4.2.0.jar batik-all-1.7.jar commons-io-1.
 3.1.jar commons-logging-1.0.4.jar fop.jar xml-apis-ext-1.3.04.jar xml
 graphics-commons-1.4.jar jlatexmath-minimal-1.0.3.jar jlm_cyrillic.ja
 r jlm_greek.jar vizjs.jar j2v8_win32_x86_64-3.1.6.jar j2v8_linux_x86_
 64-3.1.6.jar j2v8_macosx_x86_64-3.1.6.jar
```
If they'll be successfully loaded, the V8 engine would be used. For that, PlantUML tries to load the class with reflection:
```
public static boolean isOk() { try {
			final Class classVizJS = Class.forName("ch.braincell.viz.VizJS");
			return true;
		} catch (Exception e) {
			return false;
		}
	}

```
So that's some sort of a plantuml-plugin, but it bases on the pure JVM manifest classpath mechanism.

Now the problem is I don't know alot about the Eclipse classloader magic.
But this "magic" enables OSGi plugins with the export and import of specific functionalities against each other. And OSGi bases on MANIFEST.MF too.
That's all an area I really don't know but it's obvious that your Problem simply is that the plantuml.jar is not in the same classpath space like vizjs.jar.
I think you have to create something like an eclipse plugin which includes all according libraries together (plantuml, vizjs and J2V8) so that they'll be loaded in the same classpath space. More or less you would do the same like plantuml.jar tries to do with his own MANIFEST.MF, but with the eclipse plugin system. 

I hope that helps a bit.

**Comment by elab** [comment]
I'm using **asciidoctorj-diagram-1.5.16** in a Maven build on Windows and got the same error.
After some investigations I added 'vizjs.jar' to the list of JARs in "extension.rb" inside asciidoctorj-diagram-1.5.16.jar. Now the error was about loading j2v8 JS engine. Therefore I added the entries for j2v8 jars, too.

Here are the changes to **asciidoctorj-diagram-1.5.16.jar\gems\asciidoctor-diagram-1.5.16\lib\asciidoctor-diagram\plantuml\extension.rb**:


      JARS = [
          'plantuml-1.3.13.jar',
          'plantuml.jar',
          'jlatexmath-minimal-1.0.5.jar',
          'batik-all-1.10.jar',
          'vizjs.jar',                   // <--
          'j2v8_win32_x86-3.1.6.jar',    // <--
          'j2v8_win32_x86_64-3.1.6.jar', // <--
          'j2v8_linux_x86_64-3.1.6.jar', // <--
          'j2v8_macosx_x86_64-3.1.6.jar' // <--
      ].map do |jar|
        File.expand_path File.join('../..', jar), File.dirname(__FILE__)
      end
      Java.classpath.concat JARS

I also copied these JAR files to the folder **asciidoctorj-diagram-1.5.16.jar\gems\asciidoctor-diagram-1.5.16\lib** which now contains the following JARs:

    batik-all-1.10.jar
    ditaa-1.3.13.jar
    ditaamini-0.11.jar
    j2v8_linux_x86_64-3.1.6.jar    <---
    j2v8_macosx_x86_64-3.1.6.jar   <---
    j2v8_win32_x86_64-3.1.6.jar    <---
    j2v8_win32_x86-3.1.6.jar       <---
    jlatexmath-minimal-1.0.5.jar
    plantuml.jar
    plantuml-1.3.13.jar
    server-1.3.13.jar
    vizjs.jar                      <---

It works now :)

By the way, I'm setting the system property **GRAPHVIZ_DOT=vizjs** directly in Maven's pom.xml using properties-maven-plugin:

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>set-system-properties</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <property>
                                    <name>GRAPHVIZ_DOT</name>
                                    <value>vizjs</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            ...			
        </plugins>
    </build>
